name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 32-bit
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x86'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install selenium beautifulsoup4 pandas

    - name: Build EXE
      run: |
        pyinstaller --onefile --console C:\Users\phuch\Documents\autosp\dataproduct.py

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: dataproduct
        path: dist/dataproduct.exe
